### ISSUE TITLE
workaround to replace old "sourceMap" configuration parameter

### ISSUE THREAD

**Issue by oupala** [ksmithut/metalsmith-uglify#10]
Is there a workaround to replace the old `sourceMap` configuration parameter :

```
.use(uglify({ // minify and concat javascript
    concat: 'js/app.min.js',
    sourceMap: true
}))
```

I'm thinking about something like another metalsmith plugin to achieve this task ? Or is it best located in metalsmith-ulgify module, when you'll have time to re-add this feature ?

**Comment by ksmithut** [comment]
I think I might have some time this weekend to take a look. Before, it overcomplicated the code because the sourcemapping in uglifyjs2 didn't support strings or buffers, which is how metalsmith passes files along. Hopefully uglifyjs supports this now :)

**Comment by ksmithut** [comment]
Alright, I've got some initial work done on this front. It's published on npm under version `1.1.0`. It still doesn't support concatenating, but I plan to work in that piece tomorrow. Here's the relevant piece in the documentation:

- **`options.sourceMap`** (Boolean|String|Function) Default: `false`

  This indicates whether or not you wish to add a source map to the files. If
  you indicate `true`, it will add an additional file to the output, which will
  be named the name of the minified file, plug `.map`. So if you have a file
  named `app.js`, it will be minified to `app.min.js` and the map file will be
  named `app.min.js.map`.

  If you pass a string, it will use that name, but you can also specify tokens
  for dynamic path generation. So in the above example, if you had a file named
  `js/app.js`, it would generate a file named `js/app.min.js`. If you passed
  `'{{dir}}/{{name}}.map'` into the sourcemap options, it would generate the map
  file at `js/app.min.js.map`. If you passed `'maps/{{name}}.map'`, it
  would generate the file at `'maps/app.min.js.map'`.

  If you pass a function, it will be called for each matching file with the path
  of the minified file as it's argument. You need to return the path to the
  source map file to generate.

**Comment by ksmithut** [comment]
@oupala I've added the `concat` option, but through my testing, I've unveiled a nasty bug in the uglify library. It comes when multiple files are being passed into the minify function as strings and source maps are being generated. It seems that the source map only references the first file in list of files. Concatenating should work just fine though. Just pass the filepath of the new file you want generated in the `concat` option.

Let me know how that works, and I'll set aside some time this week to look into the concatenating/source map issue later this week.

**Comment by oupala** [comment]
Thanks @ksmithut for adding `sourceMap` and `concat` options. The two options seems to work well tough I can see some problems :

- the `concat` option does not allow to pass an order, in my case, I would like to be able to have the following configuration :

``` 
filter: ['js/jquery-2.1.1.min.js', 'js/bootstrap/*.js', 'js/**/*.js']
```

and I get the following error :

``` 
Error: uglify: Failed to minify : TypeError: Cannot read property 'figure_out_scope' of null
```

**Comment by oupala** [comment]
I should create a new issue for this problem.
