### ISSUE TITLE
Concatenation and source maps

### ISSUE THREAD

**Issue by alexturpin** [ksmithut/metalsmith-uglify#15]
Hey all,

I've recently started using metalsmith-uglify for a project and am running into the source maps issue happening when concatenating multiple files. Seems as if the sourcemaps generated by Uglify only refers to the very first file passed through concatenation even when the error is in other files. The line number is correct however. 

I've seen this problem be mentioned in various places in the project and issues. I am just wondering today whether someone has come up with solution or alternative?

Thank you very much

**Comment by ksmithut** [comment]
It's been a while since I've looked at any upgrades to uglifyjs. That was the main pain point for me because uglifyjs doesn't really support passing in strings to be uglified very well. They primarily handle the io part of it, and since metalsmith is handing the file io piece, uglifyjs has to offer up a way to support sourcemaps without file io. I can take a look again sometime this week to see if uglifyjs has fixed any of the issues I've brought up with them.

**Comment by alexturpin** [comment]
Hey @ksmithut ! Thanks for the prompt answer.

Ah I understand the issue. So right now it seems as if metalsmith-uglify would be 3 versions of uglifyjs behind. They don't have a changelog but I perused the commits and perhaps this would be what we're looking for? https://github.com/mishoo/UglifyJS2/commit/85924bb32e1c27f555aad1651f4575b45bcbadb1

This allows to pass an object of file names / contents instead of just an array of contents when working from strings.

I tried my best to implement this new feature locally on my copy of metalsmith-uglify and didn't quite manage. On first try I just modified the `contents` variable to match the file name / contents format. That resulted in the same problem as before. Then on whim I tried commenting out the line that did `mangled.map = processSourceMap(files, mangled.map);` and I started seeing the right file names in dev tools when there was an error! Unfortunately the file that would open in dev tools was empty. 

Perhaps there's a mix of both solutions that could fix this problem once and for all but I'm not sure what it is! Maybe with a better understanding of the plugin than me you'd have better luck.

**Comment by ksmithut** [comment]
Ah, 3 versions behind would probably do it. I'll see what I can manage this week. Let me know what if you find if you find anything new. Thanks so much for your effort 😄

**Comment by alexturpin** [comment]
No worries, thank you so much for your continued support on this project! I'll let you know if I have time to play with it some more this week.

**Comment by ksmithut** [comment]
Just an update, I've honestly not had much time to dedicate to some of my side projects, but am hoping to be able to dedicate more time this week and the next to resolve some of these issues.

**Comment by alexturpin** [comment]
Thanks a lot for letting me know @ksmithut ! If I happen to find something else that might help I'll be sure to let you know.

**Comment by alexturpin** [comment]
@ksmithut Okay, I took the time to fix it properly and have submitted a PR.

**Comment by ksmithut** [comment]
@alexturpin Thank you so much for your work. I've publish a new version with your changes to npm, version 1.4.0.

**Comment by alexturpin** [comment]
No worries, happy I was able to help! Thanks for merging and publishing a new version so fast!
