### ISSUE TITLE
Can appending '.min' be optional?

### ISSUE THREAD

**Issue by chaucerbao** [ksmithut/metalsmith-uglify#17]
I noticed you rename the output file rather than update the file in-place. Can this be optional?

https://github.com/ksmithut/metalsmith-uglify/blob/master/lib/normalize-options.js#L106

**Comment by ksmithut** [comment]
Yes, seems reasonable. I believe I used to have it as an option, but removed it in a major version release because I didn't like the way I was doing it. I'll add this back in.

**Comment by ksmithut** [comment]
@chaucerbao I have added a `nameTemplate` option which allows you to customize the filename. The default option is `[name].min.[ext]`. You can change it to `[name].[ext]` replace the original file in the generated output. Let me know if this fills your need.

**Comment by chaucerbao** [comment]
Nice! Thanks.
